/**
 * Official unlock requirements for system badges and medals.
 * Teacher custom awards (criteria_type = manual) are not listed here.
 *
 * Badges are early milestones. Medals are larger achievements.
 * Level is floor(xp / 100) + 1, so level 5 = 400 XP, level 10 = 900 XP.
 */

export const SYSTEM_BADGES = [
  {
    name: "First Steps",
    description: "Complete 1 lesson",
    icon: "school",
    color: "#42A5F5",
    criteriaType: "lessons_completed",
    criteriaValue: 1,
    difficulty: null,
    xpBonus: 10,
  },
  {
    name: "Lesson Builder",
    description: "Complete 5 lessons",
    icon: "school",
    color: "#1D4ED8",
    criteriaType: "lessons_completed",
    criteriaValue: 5,
    difficulty: null,
    xpBonus: 25,
  },
  {
    name: "Quiz Champion",
    description: "Pass 3 quizzes",
    icon: "quiz",
    color: "#66BB6A",
    criteriaType: "quizzes_passed",
    criteriaValue: 3,
    difficulty: "medium",
    xpBonus: 20,
  },
  {
    name: "Game Starter",
    description: "Complete 3 games",
    icon: "sports_esports",
    color: "#8B5CF6",
    criteriaType: "games_completed",
    criteriaValue: 3,
    difficulty: null,
    xpBonus: 20,
  },
  {
    name: "XP Collector",
    description: "Earn 100 XP",
    icon: "star",
    color: "#FFA726",
    criteriaType: "xp",
    criteriaValue: 100,
    difficulty: null,
    xpBonus: 15,
  },
  {
    name: "Rising Star",
    description: "Earn 500 XP",
    icon: "auto_awesome",
    color: "#AB47BC",
    criteriaType: "xp",
    criteriaValue: 500,
    difficulty: null,
    xpBonus: 50,
  },
  {
    name: "Streak Starter",
    description: "Learn 3 days in a row",
    icon: "local_fire_department",
    color: "#EF4444",
    criteriaType: "streak",
    criteriaValue: 3,
    difficulty: null,
    xpBonus: 15,
  },
  {
    name: "Level Scout",
    description: "Reach level 3",
    icon: "military_tech",
    color: "#0EA5E9",
    criteriaType: "level",
    criteriaValue: 3,
    difficulty: null,
    xpBonus: 15,
  },
  {
    name: "Perfect Start",
    description: "Score 100% on 1 quiz",
    icon: "workspace_premium",
    color: "#F59E0B",
    criteriaType: "perfect_quiz",
    criteriaValue: 1,
    difficulty: null,
    xpBonus: 25,
  },
];

export const SYSTEM_MEDALS = [
  {
    name: "Bronze Climber",
    description: "Reach level 5",
    tier: "bronze",
    icon: "military_tech",
    criteriaType: "level",
    criteriaValue: 5,
  },
  {
    name: "Silver Scholar",
    description: "Reach level 8",
    tier: "silver",
    icon: "military_tech",
    criteriaType: "level",
    criteriaValue: 8,
  },
  {
    name: "Diamond Achiever",
    description: "Reach level 10",
    tier: "diamond",
    icon: "diamond",
    criteriaType: "level",
    criteriaValue: 10,
  },
  {
    name: "Legendary Learner",
    description: "Reach level 20",
    tier: "legendary",
    icon: "workspace_premium",
    criteriaType: "level",
    criteriaValue: 20,
  },
  {
    name: "Perfect Score",
    description: "Score 100% on 1 quiz",
    tier: "gold",
    icon: "workspace_premium",
    criteriaType: "perfect_quiz",
    criteriaValue: 1,
  },
  {
    name: "Top Contender",
    description: "Reach top 3 on the leaderboard",
    tier: "platinum",
    icon: "emoji_events",
    criteriaType: "leaderboard_rank",
    criteriaValue: 3,
  },
  {
    name: "Campus Champion",
    description: "Reach #1 on the leaderboard",
    tier: "legendary",
    icon: "emoji_events",
    criteriaType: "leaderboard_rank",
    criteriaValue: 1,
  },
  {
    name: "XP Titan",
    description: "Earn 1,000 XP",
    tier: "gold",
    icon: "star",
    criteriaType: "xp",
    criteriaValue: 1000,
  },
  {
    name: "Unstoppable Streak",
    description: "Learn 14 days in a row",
    tier: "platinum",
    icon: "local_fire_department",
    criteriaType: "streak",
    criteriaValue: 14,
  },
  {
    name: "Quiz Master",
    description: "Pass 10 quizzes",
    tier: "gold",
    icon: "quiz",
    criteriaType: "quizzes_passed",
    criteriaValue: 10,
  },
  {
    name: "Lesson Legend",
    description: "Complete 15 lessons",
    tier: "platinum",
    icon: "school",
    criteriaType: "lessons_completed",
    criteriaValue: 15,
  },
  {
    name: "Game Veteran",
    description: "Complete 10 games",
    tier: "diamond",
    icon: "sports_esports",
    criteriaType: "games_completed",
    criteriaValue: 10,
  },
];
