USE eduquest;

CREATE TABLE IF NOT EXISTS ai_review_drafts (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  teacher_id INT UNSIGNED NOT NULL,
  course_id INT UNSIGNED NOT NULL,
  lesson_id INT UNSIGNED NULL,
  source_type ENUM('ai_quiz', 'ai_game', 'ai_content', 'lesson_extras', 'manual') NOT NULL DEFAULT 'manual',
  status ENUM('draft', 'published', 'archived', 'discarded') NOT NULL DEFAULT 'draft',
  title VARCHAR(255) NULL,
  source_text MEDIUMTEXT NULL,
  quiz_json JSON NULL,
  game_json JSON NULL,
  learning_objectives_json JSON NULL,
  lesson_summary_json JSON NULL,
  generation_meta JSON NULL,
  quiz_id INT UNSIGNED NULL,
  game_id INT UNSIGNED NULL,
  ai_generated TINYINT(1) NOT NULL DEFAULT 1,
  teacher_edited TINYINT(1) NOT NULL DEFAULT 0,
  generated_by INT UNSIGNED NULL,
  published_by INT UNSIGNED NULL,
  published_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_review_teacher FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_review_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_review_lesson FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_review_quiz FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_review_game FOREIGN KEY (game_id) REFERENCES educational_games(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_review_generated_by FOREIGN KEY (generated_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_review_published_by FOREIGN KEY (published_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ai_review_teacher_status (teacher_id, status),
  INDEX idx_ai_review_course (course_id)
) ENGINE=InnoDB;
